const AUTO = 1;
const AUTO_BLEED = 2;
const AUTO_MARKS = 3;
const LETTER_PORTRAIT = 4;
const LETTER_LANDSCAPE = 5;
const A4_PORTRAIT = 6;
const A4_LANDSCAPE = 7;

export {
  AUTO,
  AUTO_BLEED,
  AUTO_MARKS,
  LETTER_PORTRAIT,
  LETTER_LANDSCAPE,
  A4_PORTRAIT,
  A4_LANDSCAPE,
};
